name 'chef-client-hab-distro'
maintainer 'Chef Software, Inc'
maintainer_email 'support@chef.io'
license 'Apache-2.0'
description 'Installs/Configures chef-client-hab-distro'
long_description 'Installs/Configures chef-client-hab-distro'
version '0.1.0'
chef_version '>= 13.0'

issues_url 'https://github.com/chef-cft/chef-client-hab-distro/issues'
source_url 'https://github.com/chef-cft/chef-client-hab-distro'
